### ISSUE TITLE
领地内物品意外丢弃无法拾取

### ISSUE THREAD

**Issue by MengYang8481** [Redbeanw44602/iLand#18]
很多人购买领地过后会保持默认配置，默认配置“允许捡起物品”是默认关闭的而“允许丢弃物品”则是开启的。因此，可能会在别人领地内意外按到Q，把手里的物品丢弃（可能就是贵重物品），然后领地主人不在线，被清理插件直接清理掉，而清理插件是防止服务器卡顿的必要插件，是尽可能不要移除的。我对新版本iland针对此问题有以下建议：1.保持现有默认配置，检测物品丢弃者与物品拾取者是否为同一个人，如果是则可以无视领地配置，可以捡起；2.把购买领地后的默认配置项“允许捡起物品”与“允许丢弃物品”全部改为开或关。希望iland能在bds圈越来越好啦~（凭着记忆写的默认配置项名字可能略有出入，能看懂就行）

**Comment by Redbeanw44602** [comment]
应当让清理插件通过ILAPI对接iLand。

如果你服有默认允许捡起物品的需要，请参考文档关闭相关监听器。
