### ISSUE TITLE
关于iland领地冲突问题

### ISSUE THREAD

**Issue by CNDogc** [Redbeanw44602/iLand#20]
两个领地都是我自己圈的...明明并没有冲突，但是提示冲突或过近，详细信息没有坐标提示：包含
![image](https://user-images.githubusercontent.com/92175245/160396285-81c3e24c-35d8-4ef4-8be8-cc56ed9b113b.png)

**Comment by Redbeanw44602** [comment]
你应当提供两个领地的对角坐标。

包含的意思是你圈的这个领地直接完全包含了某个领地。

如果要关闭近距离检测，请查阅文档。

**Comment by CNDogc** [comment]
一块是-34447,-64,33963到-34437,320,33957   
另一块是-34445,78,33971到-34439,83,33977
