### ISSUE TITLE
正在被使用的高炉、熔炉、火炉无权限会被打开

### ISSUE THREAD

**Issue by MengYang8481** [Redbeanw44602/iLand#21]
RT，没有权限的情况下能打开如题的三个容器并且能拿出物品，配置项已确保关闭

**Comment by MengYang8481** [comment]
bds 1.18.12 ，ll 2.1.5 ，iland 2.82，在2.83更新日志中未看见修复

**Comment by Redbeanw44602** [comment]
收到。我现在被封控在学校，等我回去后检查一下
