### ISSUE TITLE
领地保护不完善（流体）

### ISSUE THREAD

**Issue by MengYang8481** [Redbeanw44602/iLand#22]
RT，点墙上可以直接放水或者岩浆破坏领地内植物或者建筑
![无标题](https://user-images.githubusercontent.com/23436744/162605245-ce7287e5-0a8d-43b1-90c0-c07b1c1aca11.png)

**Comment by Redbeanw44602** [comment]
收到，目前我正在被封控在学校，等回家了我检查一下
