### ISSUE TITLE
领地内其他人可以放蜡烛和海泡菜

### ISSUE THREAD

**Issue by Arnolwutong** [Redbeanw44602/iLand#31]
领地内其他人可以可以放蜡烛和海泡菜
bds版本1.18.32
ll版本2.2.3
iland版本2.84
![QQ图片20220511193751](https://user-images.githubusercontent.com/95761056/167840983-7e084b0d-3017-4f22-89d7-18b7a4e09de1.jpg)

**Comment by Redbeanw44602** [comment]
放置控制问题不处理，请反馈给LL
