### ISSUE TITLE
关于在其人领土上还能挖掘方块

### ISSUE THREAD

**Issue by nansheng181** [Redbeanw44602/iLand#32]
在其他人的领地上还能破坏方块，我这边也没冲突，所有文件也没动，监视器也都开着，但还是能挖掘方块

**Comment by nansheng181** [comment]
请管理员解决一下我的问题，谢谢

**Comment by Redbeanw44602** [comment]
你是领地管理员吗

**Comment by nansheng181** [comment]
不是我都测试了我还特意吧我的游戏op 领地插件的op都给卸了还调了生存，其他的限制都能正常运行，就是挖方块的监视器不管用，还是能挖

**Comment by nansheng181** [comment]
求求管理帮我这个小白吧

**Comment by nansheng181** [comment]
我不是什么都没测试就直接来问的，是这个问题真的在我理解范围外，请不要骂我，帮帮我谢谢

**Comment by nansheng181** [comment]
其他的都不能破坏就是可以破坏方块

**Comment by Redbeanw44602** [comment]
经过群友测试，该问题无法复现。
请尝试：
1. 更新到最新的BDS和LiteLoader
2. 重新安装iLand
3. 检查控制项是否开启、检查监听器是否被关闭

如有问题，请重新打开该issue。
