### ISSUE TITLE
Trapdoor settings somehow ignored and effected by door settings

### ISSUE THREAD

**Issue by HongyiMC** [Redbeanw44602/iLand#39]
door setting is interfering the trapdoor setting

**Comment by HongyiMC** [comment]
[https://github.com/LiteLScript-Dev/iLand-Core/pull/40](url)

**Comment by HongyiMC** [comment]
[https://github.com/LiteLScript-Dev/iLand-Core/pull/40/commits/85c1ab5aa3e63c83aa89a7b4b5d42312031a9da5](url)

**Comment by Redbeanw44602** [comment]
Sorry, iLand has stopped feature updates for this branch.

Version 2.90 is in production and I'm taking time out of my preparation for the Gaokao (a stupid but important exam for Chinese students) to work on it. Hope you understand, but it should be released soon.

The new plugin system will be much better, and you should be very uncomfortable when modifying plugins currently.

**Comment by HongyiMC** [comment]
Can we merge this so it can be fixed?

**Comment by Redbeanw44602** [comment]
merged.
