### ISSUE TITLE
发现报错

### ISSUE THREAD

**Issue by CNDogc** [Redbeanw44602/iLand#43]
23:22:16 ERROR [LiteLoader] C++ Uncaught Exception Detected!
23:22:16 ERROR [LiteLoader] There is already a command named land
23:22:16 ERROR [LiteLoader] [failed to get stacktrace]
23:22:16 ERROR [LiteLoader] In API: McClass::regConsoleCmd
23:22:16 ERROR [LiteLoader] In Plugin: iLand

**Comment by Redbeanw44602** [comment]
看置顶issue
