### ISSUE TITLE
Failed in buy land but still lost their coin

### ISSUE THREAD

**Issue by AngelliaX** [Redbeanw44602/iLand#6]
Player doesnt get the land but they still lost their coin

How to reproduce:
1) /land new -> /land a -> /land b -> land buy
2) Now, it will display the "title.buyland.ordersaved" text
3) Use a stick and break a block in land, it will popup an UI, when i click Buy, it will return to step 2), and lost coin without having that land

**Comment by moxisuki** [comment]
may update your lxl(？)

**Comment by Redbeanw44602** [comment]
This is a problem with LXL. It has been fixed in 0.5.2. Please upgrade your LXL.
